OPENAI_ENDPOINT = "https://.........openai.azure.com/"
OPENAI_KEY = "........."
OPENAI_MODEL = "gpt4-o"

STORAGE_ACCOUNT_NAME = "......."
STORAGE_ACCOUNT_KEY = "......."
CONTAINER_NAME = "app"

CLIENT_ID = "......."
CLIENT_SECRET = "......."
TENANT_ID = "......."
SCOPE = ["User.Read Group.ReadWrite.All DeviceManagementManagedDevices.ReadWrite.All DeviceManagementManagedDevices.PrivilegedOperations.All DeviceManagementApps.ReadWrite.All"]
REDIRECT_URI = "http://localhost:8501/"


BING_SECRET = "....."